[package]
name = "ntge"
version = "0.1.0"
authors = ["Yisi Liu <yisiliu@gmail.com>", "Cirno Mainasuk", "Tlaster", "Brad Gao"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
