name: Android

on:
  push:
    paths:
      - "ntge-core/**"
      - "NtgeCore-Android/**"
  pull_request:
    paths:
      - "ntge-core/**"
      - "NtgeCore-Android/**"

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: add rust target
        run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
      - name: grant execute permission for gradlew
        working-directory: ./NtgeCore-Android
        run: chmod +x ./gradlew
      - name: build
        working-directory: ./NtgeCore-Android
        run: ./gradlew clean build
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          working-directory: ./NtgeCore-Android
          api-level: 29
          script: ./gradlew connectedCheck

